### ISSUE TITLE
FSharp.Charting shows nothing under FSI 14.0.23020.0

### ISSUE THREAD

**Issue by danslapman** [fslaborg/FSharp.Charting#101]
Hello!
Tonight i faced an issue trying to show a simple graph.
The code:
```fsharp
#load "packages/FSharp.Charting/FSharp.Charting.fsx"
open FSharp.Charting
Chart.Line [ for x in 0 .. 10 -> x, x*x ]
```
being executed with
    fsi line.fsx
shows nothing.
Fsi version is 14.0.23020.0 (shipped with visual studio 2015)

**Comment by tpetricek** [comment]
That is odd!

Are you running the code in F# Interactive? Can you include the full output (including the "val" lines printed by F# Interactive?)

**Comment by danslapman** [comment]
I'm running code above by saving it in a file and running by "fsi file.fsx"

**Comment by tpetricek** [comment]
Hmm, does FSI close immediately after running the code? Can you add `System.Console.ReadLine() |> ignore` to the end ?

**Comment by danslapman** [comment]
Yes, it closes after a second or two. Adding `System.Console.ReadLine() |> ignore` didn't change anything.

**Comment by tpetricek** [comment]
I see, when you run things using `fsi.exe`, it does not print any output - which is what normally triggers the function to display the chart. The following works for me:

    #load "packages/FSharp.Charting/FSharp.Charting.fsx"
    open FSharp.Charting
    Chart.Line [ for x in 0 .. 10 -> x, x*x ]
    |> Chart.Show // Display the chart explicitly
    System.Console.ReadLine() // Wait for user input before closing chart

**Comment by danslapman** [comment]
Yes, this works nice, thanks!
