### ISSUE TITLE
Labels disappear at 10 columns

### ISSUE THREAD

**Issue by cmmurray** [fslaborg/FSharp.Charting#103]
Maybe this is a known limitation (?) but it seems like every other column label is dropped once there are 10 of them.

This works fine..

```
[1 .. 9]
|> Seq.map (fun x -> x.ToString(),x)
|> Chart.Column
```

This fails

```
[1 .. 10]
|> Seq.map (fun x -> x.ToString(),x)
|> Chart.Column
```

**Comment by tpetricek** [comment]
I think this is just a design issue - they're there, but not rendered so that everything fits. I guess increasing the chart size or making label fonts smaller should get them back.
