### ISSUE TITLE
Mac OS X: The field, constructor or member 'Stock' is not defined

### ISSUE THREAD

**Issue by Darkkey** [fslaborg/FSharp.Charting#107]
Does Mac OS X/crossplatform version of library support Stocks/Candlesticks? Because if I try to follow this sample: http://fslab.org/FSharp.Charting/StockAndCandlestickCharts.html
, I'm getting "error FS0039: The field, constructor or member 'Stock' is not defined"
However, Chart.Line (and other simple charts) works correct.

**Comment by dsyme** [comment]
No, it's not supported.  A pull request would be welcome.

**Comment by sebfia** [comment]
I'll do it!

**Comment by sebfia** [comment]
Done, see PR #131

**Comment by dsyme** [comment]
@sebfia  Great!

If there's any chance we could "modernize" the Gtk support that would be great.  For example
* Update to Gtk3??
* Update OxyPlot to latest?
* ...

Also better docs on what is required to install etc.
