### ISSUE TITLE
using FSharp.Charting

### ISSUE THREAD

**Issue by FaguiCurtain** [fslaborg/FSharp.Charting#111]
hi this is not really an issue i believe with the package, but I have trouble using it.
I've installed it for VS2015. 
i've got no problem using it in F# interactive

However, in my solution, i've referenced the library in a .fsx file with 
# r "System.Windows.Forms.DataVisualization.dll"
# nowarn "211"
# I **SOURCE_DIRECTORY**
# I "lib/net40"
# I @"C:\Users\Fagui\Documents\GitHub\Learning Fsharp\Algos\Algos\packages\FSharp.Charting.0.90.13\lib\net40"
# r "FSharp.Charting.dll"

open FSharp.Charting
module FsiAutoShow = 
    fsi.AddPrinter(fun (ch:FSharp.Charting.ChartTypes.GenericChart) -> ch.ShowChart() |> ignore; "(Chart)")

then in my source code i do the following

open System
open System.Collections
open System.Collections.Generic
open System.IO

open FSharp.Core

open System.Windows
**open System.Drawing**
**open FSharp.Charting**
(...)
**let C = Chart.Point (Array.toList cities)**

i get the following compilation error

Error       The type referenced through 'System.Drawing.Color' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Drawing'. Algos   C:\Users\Fagui\Documents\GitHub\Learning Fsharp\Algos\Algos\TSP.fs  48  

how do i reference System.Drawing ? indeed in the solution explorer, i don't see it listed in the references. is there another package to install ? thanks v much

**Comment by simra** [comment]
I think adding '#r System.Drawing.dll' to your script should be sufficient. It's a standard .NET assembly.

**Comment by FaguiCurtain** [comment]
hi
this doesn't work for me
i have added a line in my .fsx script

#r "System.Drawing.dll"

but i still dont see it listed in the references of the Solution explorer. 
by the way where is this file supposed to be, when i look for it in File explorer it looks like its in a hidden folder C:/Windows/WinSxS/msil_system.drawingb03f5f....

**Comment by FaguiCurtain** [comment]
by the way i have also an iMAC (running on MacOS X 10.11.3 El Capitan)  and i don't get how to install the library properly as well on Xamarin Studio
I've downloaded from Nuget  FSharp.Charting.Gtk which i believe is the cross platform version

I'm including the .fsx file

```

#nowarn "211"
#nowarn "40"

// When compiling, a reference to this is needed

#r "FSharp.Compiler.Interactive.Settings.dll"

// On windows we just reference the DLLs. On Mono we must reference them in ../gtk-sharp-2.0 relative
// to the Mono installation.
//
// On Mono OSX/Linux we could just use
//
//#r "../gtk-sharp-2.0/gtk-sharp.dll"
//#r "../gtk-sharp-2.0/gdk-sharp.dll"
//#r "../gtk-sharp-2.0/atk-sharp.dll"
//#r "../gtk-sharp-2.0/glib-sharp.dll"
//
// and on .NET on Windows
//
//#r "gtk-sharp.dll"
//#r "gdk-sharp.dll"
//#r "atk-sharp.dll"
//#r "glib-sharp.dll"

#I "/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gtk-sharp-2.0"
#I "/usr/lib/mono/gtk-sharp-2.0"

#r "gtk-sharp.dll"
#r "gdk-sharp.dll"
#r "atk-sharp.dll"
#r "glib-sharp.dll"

// In F# 2.0, 3.0 and 3.1, the resolution of #r paths in #load'd scripts is NOT relative to the directory where the script
// lives. However, the resolution of #I paths is, and the #I paths have local file scope.
//
// This means that using #I __SOURCE_DIRECTORY__ is sufficient to enable local resolution of #r and #I paths within an included script file.

#I __SOURCE_DIRECTORY__
#I @"/Users/francois-guillaume.rideau/Projects/MyiMAC/MyAlgos/packages/FSharp.Charting.Gtk.0.90.12/"
#r "lib/net40/OxyPlot.dll"
#r "lib/net40/OxyPlot.GtkSharp.dll"
#r "lib/net40/FSharp.Charting.Gtk.dll"

open System
let verifyMac () = 
    try
        use p=new System.Diagnostics.Process()
        p.StartInfo.FileName<-"uname"
        p.StartInfo.Arguments<-"-s"
        p.StartInfo.RedirectStandardOutput<-true
        p.StartInfo.UseShellExecute<-false
        p.StartInfo.CreateNoWindow<-true
        p.Start() |> ignore
        let kernalName=p.StandardOutput.ReadLine()
        p.WaitForExit()
        kernalName="Darwin"
    with
        |_ ->false

let isMac = 
    match Environment.OSVersion.Platform with
        | PlatformID.MacOSX -> true
        | PlatformID.Unix -> verifyMac()
        | _ -> false
// Workaround bug http://stackoverflow.com/questions/13885454/mono-on-osx-couldnt-find-gtksharpglue-2-dll
//
// There is no harm if this code is run more than once.

if isMac then 
    let prevDynLoadPath = Environment.GetEnvironmentVariable("DYLD_FALLBACK_LIBRARY_PATH")
    let newDynLoadPath =  "/Library/Frameworks/Mono.framework/Versions/Current/lib" + (match prevDynLoadPath with null -> "" | s -> ":" + s) + ":/usr/lib"
    System.Environment.SetEnvironmentVariable("DYLD_FALLBACK_LIBRARY_PATH", newDynLoadPath)

// Initialize Gtk. There is no harm if this code is run more than once.
Gtk.Application.Init()

fsi.EventLoop <- 
 { new Microsoft.FSharp.Compiler.Interactive.IEventLoop with
   member x.Run() = Gtk.Application.Run() |> ignore; false
   member x.Invoke f = 
     let res = ref None
     let evt = new System.Threading.AutoResetEvent(false)
     Gtk.Application.Invoke(new System.EventHandler(fun _ _ ->
       res := Some(f())
       evt.Set() |> ignore ))
     evt.WaitOne() |> ignore
     res.Value.Value 
   member x.ScheduleRestart() = () }


// Add an auto-display for things of type "GenericChart"

open FSharp.Charting
module FsiAutoShow = 
    fsi.AddPrinter(fun (ch:FSharp.Charting.ChartTypes.GenericChart) -> ch.ShowChart() |> ignore; "(Chart)")
```

this is my source file
```
let printSourceLocation() = 
     printfn "Line: %s" __SOURCE_DIRECTORY__
     printfn "Source Directory: %s" __SOURCE_DIRECTORY__
     printfn "Source File: %s" __SOURCE_FILE__
printSourceLocation()

open FSharp.Charting

let cities = [(0.0,0.0);(0.0,1.0);(0.0,2.0);(0.0,3.0);(0.0,4.0);(1.0,4.0);(1.0,3.0);(1.0,2.0);(1.0,1.0);(1.0,0.0)] 

let C = Chart.Point(cities)
C.ShowChart()
```

and i get the following error

/Users/francois-guillaume.rideau/Projects/MyiMAC/MyAlgos/MyAlgos/FSharp.Charting.Gtk.fsx(1,1): Error FS0078: Unable to find the file 'FSharp.Compiler.Interactive.Settings.dll' in any of /Library/Frameworks/Mono.framework/Versions/4.4.0/lib/mono/4.5-api /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gtk-sharp-2.0 /Users/francois-guillaume.rideau/Projects/MyiMAC/MyAlgos/MyAlgos /Users/francois-guillaume.rideau/Projects/MyiMAC/MyAlgos/packages/FSharp.Charting.Gtk.0.90.12/ /Users/francois-guillaume.rideau/Projects/MyiMAC/MyAlgos/MyAlgos /Users/francois-guillaume.rideau/Projects/MyiMAC/MyAlgos/packages/FSharp.Core.4.0.0.1/lib/net40 (FS0078) (MyAlgos)

thanks

**Comment by FaguiCurtain** [comment]
If, on MacOS i try to execute the script in interactive, followed by 
```
open System.Drawing
open FSharp.Charting
let cities = [(0.0,0.0);(0.0,1.0);(0.0,2.0);(0.0,3.0);(0.0,4.0);(1.0,4.0);(1.0,3.0);(1.0,2.0);(1.0,1.0);(1.0,0.0)] 

let C = Chart.Point(cities)
C.ShowChart()
```
then i get the following error

Error: This PlotModel is already in use by some other plot view

**Comment by simra** [comment]
System.Drawing.dll is a system dll which lives somewhere under c:\windows\.net.  For .fsx files there is no expectation that the solution will add the reference- .fsx scripts are intended to be stand-alone and don't depend on project or solution files for compilation. Your script should Just Work when it comes to referencing any system dll.
It's harder for me to tell what's  happening in the  mac case on the phone- will have a look later today.

**Comment by FaguiCurtain** [comment]
well under WIN8.1,  i still have the problem that i mentioned above. i have added to the FSharp.Charting.fsx #r "System.Drawing.dll" 
the compiler doesn't complain about this, like no underlying in red of that line. so i suppose its going through.
However when i compile the solution, i still get this error

> Error The type referenced through 'System.Drawing.Color' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Drawing'.

**Comment by FaguiCurtain** [comment]
i am closing this issue as it is too old, the version has changed , computer too.
I am revisiting the package now, and experiencing some new/other problems.
