### ISSUE TITLE
Release generation

### ISSUE THREAD

**Issue by simra** [fslaborg/FSharp.Charting#112]
@dsyme @tpetricek Checking in on the steps to generate a new release. Judging from past releases, the version number gets a bump and it looks like the zip and tar.gz packages are just exported copies of the repository.  
Are any release notes generated (automagically or otherwise)?  What steps are necessary to update nuget? Does anything else need to happen?  
As far as versions are concerned: does 0.90.14 make sense?

**Comment by tpetricek** [comment]
Generally speaking, all you should need to do is to update the release notes in `RELEASE_NOTES.md` (and increment the version number there - 0.90.14 sounds good). Then you can run `build Release` and the rest should happen automatically. If it does not, we need to give you more rights :)

There is some more info about it here: http://fsprojects.github.io/ProjectScaffold/release-process.html (though I do not use the release script with passwords in there and enter them manually)

**Comment by simra** [comment]
Thanks Tomas, 
I followed the project scaffold instructions and the gh-pages repository was updated but I don't have permissions on the nuget gallery.  My nuget username is simra- could you add me to the FSharp.Charting package?
Also, it's not completely clear to me whether a GitHub release is automatically generated, or whether I need to manually upload a zip file- I didn't get to this step due to the nuget failure.

**Comment by tpetricek** [comment]
Cool, looks like we're on the right track :-). I just added you to NuGet owners - you should get an email from them. I believe the ZIP file gets uploaded automatically too.

**Comment by simra** [comment]
Thanks Tomas,
The NuGet invite link didn't work for me- maybe the invite was revoked?  Could you try again?

**Comment by tpetricek** [comment]
Just tried again...

**Comment by simra** [comment]
Success, thanks!  I'll retry the NuGet upload this evg.

**Comment by tpetricek** [comment]
Fantastic! It's great to have another maintainer who can take care of the repo! Welcome :+1:

**Comment by simra** [comment]
Sorry, one more request: access to upload FSharp.Charting.Gtk to nuget. :-)

**Comment by tpetricek** [comment]
Good point! Added just now :)

**Comment by simra** [comment]
Thanks. We are 90% there.  It looks like FSharp.Charting pre-dates a lot of the scaffold work to publish releases to GitHub.  The nuget packages are pushed, which is the important thing, but the GitHub release isn't generated.  I'm going to manually push a release and we can look into updating the Fake script.
