### ISSUE TITLE
Histogram does not apply x-axis number formatting

### ISSUE THREAD

**Issue by odkken** [fslaborg/FSharp.Charting#116]
let chart = Chart.Histogram(data).WithXAxis(LabelStyle=ChartTypes.LabelStyle.Create(Format="F6"))

Seems like the precision is fixed at 2 for histograms.  The above formatting works correctly with a FastPoint chart.

**Comment by simra** [comment]
Hmm. This raises another bug which is that Histogram can't deal with intervals smaller than 1. For instance this line produces an empty chart:
```
Chart.Histogram([for x in 1 .. 100 -> rand()],LowerBound=0.,UpperBound=1.,Intervals=0.1)
```

**Comment by simra** [comment]
Here's the line of code that's forcing the bins to 2 decimals, by creating label strings for the bins.
```
let data'' = bins |> Seq.map (fun b -> ( sprintf "%.2f" b.LowerBound), b.Count)
```

**Comment by simra** [comment]
My mistake, with respect to the sub-integer example: I set Intervals (the number of bins) less than 1.
The fix to the formatting bug is easy.  @tpetricek: if I replace the bin label strings with the raw values, is this likely to cause problems elsewhere? (Will I break a lot of charts?)
Proposed fix:
```
let data'' = bins |> Seq.map (fun b -> b.LowerBound, b.Count)
```
I verified that this fixes the reported issue.
