### ISSUE TITLE
Is there a plan to add more chart types to FSharp.Charting.Gtk? (ex. Chart.Combine)

### ISSUE THREAD

**Issue by mwbaassiri** [fslaborg/FSharp.Charting#118]
Hi,

I am trying to use the Chart.Combine chart type in Gtk, but it seems that it's not available. Is there a plan to add it?

Thanks!

**Comment by tpetricek** [comment]
The Gtk part of F# Charting is a bit less actively maintained than the WinForms part, but we're always happy to accept pull requests that add more features.

**Comment by mwbaassiri** [comment]
Ok thanks @tpetricek !
