### ISSUE TITLE
Chart not displaying - FSI looks normal

### ISSUE THREAD

**Issue by jamessdixon** [fslaborg/FSharp.Charting#119]
Can you take a look at [this ](https://github.com/jamessdixon/Kaggle.Bimbo/blob/master/Kaggle.Bimbo.Solution/Kaggle.Bimbo.FS/ExploreData.fsx) script?  When I run lines 27/28 

adjustedDemand 
|> Chart.FastPoint 

The FSI shows that the chart rendered, but nothing pops up.

> val it : ChartTypes.GenericChart = FSharp.Charting.ChartTypes+GenericChart

I do use FSharp charting on my machine in other projects like this [one](https://github.com/jamessdixon/REPL-Driven-Development/blob/master/ChickenSoftware.StockAnalyzer.Solution/ChickenSoftware.StockAnalyzer/Script.fsx), lines 16-18 and the chart renders fine

**Comment by eugene-g** [comment]
Here is the [correct lnk](https://github.com/jamessdixon/Kaggle.Bimbo/blob/83e78dc5ae0a485e3673af5a702e5795ea25860e/Kaggle.Bimbo.Solution/Kaggle.Bimbo.FS/ExploreData.fsx#L27)

**Comment by ArtemZajtsev** [comment]
Same problem

**Comment by simra** [comment]
Hi, does your bug look like issue #101? @jamessdixon, does the second chart in your script render? Are you running fsi from the command line or in a harness (eg Visual Studio or Ionide)?

**Comment by tpetricek** [comment]
How do you reference F# Charting? 

@jamessdixon If you're seeing `FSharp.Charting.ChartTypes+GenericChart`, it suggests that the printers have not been registered - are you using `#load` to load FsLab or FSharp.Charting load script?

**Comment by dsyme** [comment]
Closing out old issues
