### ISSUE TITLE
only fsi, no fsc ?

### ISSUE THREAD

**Issue by alexpanter** [fslaborg/FSharp.Charting#120]
Hi there,

I'm trying to use the FSharp.Charting library in a small script. Problem is compiling with fsc.exe - the compiler says that the module fsi does not exist. It does work fine with fsi, but I would like to compile it properly since I use an EntryPoint. Anyone knows how to fix this? Thanks in advance :))

`#I "C:\\Program Files (x86)\\NuGet\\Packages\\FSharp.Charting.0.90.14"`
`#load "FSharp.Charting.fsx"`

`open System.Windows.Forms`
`open FSharp.Charting`
`open System`

`let drawChart(b: float, n: float, v: float) =`
    `Chart.Line([ for x in 0.0 .. 0.1 .. 1.0 -> x, b * x ** (n + v) ]).ShowChart()`
    `|> Application.Run`

`drawChart(4.0, 2.0, 3.0)`

**Comment by simra** [comment]
The short answer is that you need to reference the FSharp.Charting.dll and Windows.Forms assemblies (either via a .fsproj file or on the fsc command line), and remove the #I and #load directives from your script.  I believe you can use the INTERACTIVE variable provided by the compiler to detect whether your file is compiled by fsi or fsc.  For instance see this stackoverflow link: http://stackoverflow.com/questions/28547568/f-interactive-how-to-use-precompiler-directives-when-multiple-files-reference

**Comment by tpetricek** [comment]
If the answer from @simra does not help (AFAIK, it should!), please reopen the issue.
