### ISSUE TITLE
Oxyplot.WPF backend

### ISSUE THREAD

**Issue by gsomix** [fslaborg/FSharp.Charting#124]
From the documentation:
> On Windows, F# Charting is implemented using the Data Visualization charting controls available on Windows in .NET 4.x. On OSX, F# Charting is implemented using the OxyPlot.GtkSharp charting library.

There is WPF version of oxyplot [1]. We can use it instead Data Visualization for the purposes of  	unification with OSX version. It also allows to add more types of series, e.g. heatmap and polar plots.

[1] https://www.nuget.org/packages/OxyPlot.Wpf/

**Comment by dsyme** [comment]
@gsomix I would love to see someone submit work for this

**Comment by gsomix** [comment]
@dsyme ok, I just was going to do it

**Comment by dsyme** [comment]
I'll close this old feature request.  If you can submit a Oxyplot.WPF backend that would be great
