### ISSUE TITLE
Expected chart different than Matlab/R 

### ISSUE THREAD

**Issue by jamessdixon** [fslaborg/FSharp.Charting#132]
I have a dataframe like this:
![image](https://user-images.githubusercontent.com/1394644/28266471-0f371bd2-6ac3-11e7-8dd0-63b2d31d7e6b.png)

When I load it into Matlab and call this
plot(firstSet.Lat, firstSet.Lon)

I get a chart like this
![image](https://user-images.githubusercontent.com/1394644/28266484-1e58a630-6ac3-11e7-8666-f349d399ad16.png)

Same deal with R

When I load it into FSharp like this:
type Context = CsvProvider<dataPath,HasHeaders=true,IgnoreErrors=true>
let data = Context.GetSample()
let chartData = data.Rows |> Seq.map(fun r -> float r.Lat, float r.Lon)
let chart = Chart.Line(chartData)
chart.ShowChart()

I get a chart like this
![image](https://user-images.githubusercontent.com/1394644/28266501-2c5c08f8-6ac3-11e7-81a2-1fbfe7bf4b76.png)

is this a case of incorrect default parameters?

**Comment by tpetricek** [comment]
This looks different because F# Charting uses 0 as the max value for the Y axis - I think you should be able to specify the maxValue using something like `Chart.WithYAxis` (sorry, don't know the exact name).

**Comment by jamessdixon** [comment]
that did the trick - thanks
![image](https://user-images.githubusercontent.com/1394644/28270687-61ce3d60-6ad4-11e7-9083-e5b20273d3da.png)
