### ISSUE TITLE
Log scale with zero coordinate causes crash

### ISSUE THREAD

**Issue by jdh30** [fslaborg/FSharp.Charting#35]
Showing a chart with a log scale that includes a zero coordinate causes a crash. I think  this should ignore zero elements.

**Comment by simra** [comment]
FurtherSamples.fsx contains a log plot with input data containing (0,0). I tested log axes for both x and y coordinates and saw no crash.  I suggest this issue be closed unless someone can produce a repro.

**Comment by dsyme** [comment]
Hi @simra  - would you be interested in becoming a co-maintainer of this repo?
