### ISSUE TITLE
Site broken on https

### ISSUE THREAD

**Issue by haf** [fslaborg/FSharp.Charting#56]
![screen shot 2014-11-01 at 16 33 17](https://cloud.githubusercontent.com/assets/193115/4872266/829767e6-61dc-11e4-9add-fe7106c8f20d.png)

And

![screen shot 2014-11-01 at 16 34 23](https://cloud.githubusercontent.com/assets/193115/4872269/960829be-61dc-11e4-9a7d-a33fb2288907.png)

**Comment by dsyme** [comment]
Closing this, I think it's a general issue using HTTPS with http://fslab.org now?

**Comment by haf** [comment]
You mean that there's no HTTPS support on fslab at all now?

**Comment by tpetricek** [comment]
Looks like it. What do I need to do to enable this? (The whole page is hosted on normal Github's gh-pages.)

**Comment by dsyme** [comment]
Searching for "github pages https custom domain" in google brings up what look to be useful guides
