### ISSUE TITLE
Animated Charts

### ISSUE THREAD

**Issue by forki** [fslaborg/FSharp.Charting#64]
I have a clustering algorithm which generates 14 Charts (for every optimization step one)
I'd like to combine these into a small "movie". Is this possible?

**Comment by tpetricek** [comment]
You should be able to use `LiveChart.<YourChartType>`. This has an overload taking `IObservable<'T>` for *incremental* charts, but also an overload taking `IObservable<#seq<'T>>` for charts that replace the whole content at each step.

**Comment by forki** [comment]
I'm not sure if the LibeCharts can help since I have a combined chart. I create k Point charts and combine them using Chart.Combine.

My current idea is to use `SaveChartAs` and somehow create the movie via other .NET API (which I don't know yet)

**Comment by dsyme** [comment]
Closing out old questions
