### ISSUE TITLE
NuGet package needs to be updated as it's pointing to wrong urls and causing paket to fail

### ISSUE THREAD

**Issue by ovatsus** [fslaborg/FSharp.Charting#70]
![image](https://cloud.githubusercontent.com/assets/738761/7215239/57cc5878-e5c6-11e4-9a79-2d8c9dfc75c4.png)

**Comment by dsyme** [comment]
Done (can you double check please?)

**Comment by ovatsus** [comment]
Yes, if I update to 0.9.10 there's no error any more
