### ISSUE TITLE
Does FS.Charting support Error Bar Charts?

### ISSUE THREAD

**Issue by simra** [fslaborg/FSharp.Charting#73]
I'm interested in this functionality:
https://msdn.microsoft.com/en-us/library/dd456729.aspx

Thanks,
Rob

**Comment by dsyme** [comment]
Yes, just grab the latest FSharp.Charting nuget package and use 

    open FSharp.Charting
    Chart.ErrorBar [ for i in 0.0 .. 5.0 .. 99.0 -> (i, i*i*0.90, i*i, i*i*1.10) ]

cheers!
don

**Comment by simra** [comment]
Thanks, I'll give it a whirl.
