### ISSUE TITLE
Where is the 'official' FS.Charting git repo?

### ISSUE THREAD

**Issue by simra** [fslaborg/FSharp.Charting#74]
This page:
http://fslab.org/FSharp.Charting/contributing.html
links to this (non-existent) issue list:
https://github.com/fsharp/FSharp.Charting/issues
which redirects to this (empty) PR page:
https://github.com/fsharp/FSharp.Charting/pulls

The list I'm posting to now seems to be a lot more active, but I arrived at the earlier pages through google searches. Does the Contributing page on fslab.org just need updating?

**Comment by tpetricek** [comment]
Thanks for reporting this - you are correct, we did not update the links in "contributing" when moving the project! 

If you could send us a pull request to get this fixed, that would be fantastic. The source for the page with the issues is here: https://github.com/fslaborg/FSharp.Charting/blob/master/docs/content/contributing.md

**Comment by tpetricek** [comment]
Oh, and the answer is that the official repo is here (https://github.com/fslaborg/FSharp.Charting). We moved the project from under "github.com/fsharp", but left that there for Google.

**Comment by simra** [comment]
Thanks Tomas, I'll forward a PR in the morning.

-----Original Message-----

**Comment by simra** [comment]
I had a look at the contributing.md file and the links are correct there. So it looks like the open issue is that the update hasn't been pushed to FSLab.org. You might check that the docs are getting rebuilt and published when you accept new pull requests.

**Comment by simra** [comment]
Also, I see a similar bunch of stale links on the main FSharp.Charting page- nearly everything pointing to github. The repo itself contains no instances of "/fsharp/" so it definitely seems like a publishing issue.
