### ISSUE TITLE
Specialised Histogram Column chart

### ISSUE THREAD

**Issue by bohdanszymanik** [fslaborg/FSharp.Charting#88]
Plotting distributions is a (very) common data analysis task. The column chart in FSharp.Charting can be used for this but the default whitespace between columns isn't ideal. I noticed that in ggplot there is the [geom_bar] (http://docs.ggplot2.org/current/geom_bar.html ) and separately, the [geom_histogram] (http://docs.ggplot2.org/current/geom_histogram.html ). I suspect that geom_histogram is used much more often than geom_bar. To tweak the FSharp.Charting column chart to a histogram would primarily be just adding the customproperty "PointWidth=0.9" (and adding in the histogram binning would be useful).

Just thinking about the binning a bit further. R does a nice job there with the [hist] (https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/hist.html) function using the [pretty] (https://stat.ethz.ch/R-manual/R-devel/library/base/html/pretty.html) algorithm for choosing a default set of intervals. ggplot2 defaults to 30 intervals. If you use Histogram in [MathNet.Numerics] (http://numerics.mathdotnet.com/api/MathNet.Numerics.Statistics/Histogram.htm) you end up having to think of appropriate intervals - and if you have a 0.0 value and 0.0 as a boundary then it exceptions out - all of which means having to put more effort in to create your own binning function and deciding how to layout the data over the intervals. This is where a dedicated histogram feature in FSharp.Charting could be enticing to new users.

**Comment by bohdanszymanik** [comment]
OK, I've put a histogram chart type into a fork of Fsharp.Ccharting.fs and Fsharp.Charting.Gtk.fs (https://github.com/bohdanszymanik/FSharp.Charting) which I'll work with for while and see how it goes. Seems to work for my needs.

**Comment by tpetricek** [comment]
This looks like a very useful feature - can you create a PR (feel free to mark it as "[WiP]"), so that we can discuss it there? After a quick look at your code, I think we should be happy to merge it.

**Comment by bohdanszymanik** [comment]
Sure - hopefully I haven't introduced any other problems.
Cheers,

**Comment by bohdanszymanik** [comment]
Actually - just realised the labels aren't displaying properly on the histogram - I thought lowerbounds would be useful - I'll take a look now.

**Comment by bohdanszymanik** [comment]
Fixed for the MS Chart version - almost fixed for Gtk version.
