### ISSUE TITLE
Can the Size of a chart be modified?

### ISSUE THREAD

**Issue by ndalchau** [fslaborg/FSharp.Charting#94]
Does anyone know a way to change the size of the window programmatically? Currently, the window always defaults to the same size. However, if I use Chart.Rows or Chart.Columns, then the default size is often inappropriate. Perhaps this has not yet been implemented?

**Comment by tpetricek** [comment]
It would be nice to have a built-in support for this. At the moment, you can do this by calling `ShowChart` explicitly - this returns a Windows Forms form that you can then resize:

     let Show (width, height) (ch:ChartTypes.GenericChart) =
      let frm = ch.ShowChart()
      frm.Width <- width
      frm.Height <- height

    Chart.Line [ for x in 0.0 .. 0.1 .. 5.0 -> x, sin x ]
    |> Show (1000, 1000)

**Comment by ndalchau** [comment]
Thanks Tomas! This works nicely. Unfortunately, it won't work within Jupyter notebooks, which is something I'm playing with at the moment. Nevertheless, thanks for the pointer.

**Comment by tpetricek** [comment]
To support this in Jupyter notebooks, I think the Jupyter folks would have to do some tweaks...
